### PR TITLE
fixed issue#598

### LINKED ISSUE #598: Fatal error: Call to undefined function hash_equals() in Facebook/Helpers/FacebookRedirectLoginHelper.php on line 246
I'm trying to get the basic info for the user. I'm following official docs. I don't know how to get rid of this error.

my code is below:

`session_start();
require_once 'Facebook/autoload.php';
$fb = new Facebook\Facebook([
  'app_id' => 'XXXXX', // Replace {app-id} with your app id
  'app_secret' => 'xxxxxxxxxx',
  'default_graph_version' => 'v2.2',
  ]);

$helper = $fb->getRedirectLoginHelper();

//Get the Access Token

try {
        //access token for the account
        $access_token=$helper->getAccessToken();

} catch (Facebook\Exceptions\FacebookResponseException $e) {
        echo 'Graph returned an erorr'. $e->getMessage();
        exit;
}catch(Facebook\Exceptions\FacebookSDKException $e){
        echo 'Graph returned an erorr'. $e->getMessage();
        exit;
}

var_dump($accessToken->getValue());

$loginUrl = $helper->getLoginUrl('https://startup-sarathjasrin.c9users.io/login/');

echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';`

### PR DESCRIPTION
**Pull request by voku**
Fixes #598
-> if composer isn't used, we need to include the polyfills manually

### CODE REVIEW

File: src/Facebook/autoload.php [hunk 1]
```diff
@@ -32,6 +32,10 @@
     throw new Exception('The Facebook SDK requires PHP version 5.4 or higher.');
 }
 
+if (defined('FACEBOOK_SDK_POLYFILLS_LOADED') === false) {
```
Comment (yguedidi) [inline src/Facebook/autoload.php]: I dont think the constant use useful, you can just require once the polyfills file :)

File: tests/HttpClients/FacebookStreamHttpClientTest.php [hunk 2]
```diff
@@ -95,7 +95,7 @@ public function testCanSendNormalRequest()
         $this->streamMock
             ->shouldReceive('getResponseHeaders')
             ->once()
-            ->andReturn(explode("\n", trim($this->fakeRawHeader)));
+            ->andReturn(explode(PHP_EOL, trim($this->fakeRawHeader)));
```
Comment (yguedidi) [inline tests/HttpClients/FacebookStreamHttpClientTest.php]: must be reverted, this will broke windows servers

File: src/Facebook/autoload.php [hunk 3]
```diff
@@ -32,6 +32,10 @@
...
+    require_once __DIR__ . 'polyfills.php';
```
Comment (SammyK) [inline src/Facebook/autoload.php]: If this PR contains just this one line we should be good to go! :)

**Comment by jrgonzalezrios** [comment]
What if you requere polyfills.php in SignedRequest.php? this worked for me

**Comment by SammyK** [comment]
@voku Any way you can make the changes mentioned above so we can wrap this one up? :)

**Comment by SammyK** [comment]
I'm going to go ahead and merge this one in and finish it off based on the feedback. Thanks @voku! :)
